# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46e19ca79dd82f18060d4f7b4bb6f741d91702162f0083e6ec3c3165fb8bcde3c6ea70c1d7a00090af0011ecd627e9a7f044339d1768ea700845eb6f2be5813a

test:
  secret_key_base: 735daec98b57f09b665baeb62715577835fa5fb0ffe43f94b9c4032cda93bd9a9030380d18e263a927449356b0ecf0ecd40f275733febd521a5109902e6ecdd9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
